"""

Revision ID: 6a0e3d055ee2
Revises: 57db090eb909
Create Date: 2020-09-08 23:19:50.898943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0e3d055ee2'
down_revision = '57db090eb909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_index_key', 'users', type_='unique')
    op.drop_column('users', 'index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_index_key', 'users', ['index'])
    # ### end Alembic commands ###
