"""

Revision ID: a67fafd4728f
Revises: 6a0e3d055ee2
Create Date: 2020-09-13 00:15:07.076287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67fafd4728f'
down_revision = '6a0e3d055ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mc_username', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mc_username')
    # ### end Alembic commands ###
